// <auto-generated />
namespace FinanceApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _12121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12121));
        
        string IMigrationMetadata.Id
        {
            get { return "201402112025063_12121"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
